application: armadanetwars-hrd
version: 3_1_3
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /
  script: userlist.app

- url: /xmlrpc/
  script: main.app
  

